// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type CreateTodoPayload struct {
	Todo *Todo `json:"todo"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

func (Todo) IsNode() {}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsNode() {}
