// Code generated by github.com/stackworx-go/gqlgen-relay, DO NOT EDIT.
package integration

import (
    "bytes"
	"encoding/json"
	"io/ioutil"
	"net/http"
)

type Client struct {
	http.Client
	Url string
}

type request struct {
	Query         string                 `json:"query"`
	// OperationName string                 `json:"operationName"`
	Variables     interface{} `json:"variables"`
	Extensions    map[string]interface{} `json:"extensions"`
}

var TodosQuery = `query TodosQuery {
	todos {
		id
		text
		done
		user {
			id
			name
		}
	}
}
`



type TodosQueryPayload struct {
  Todos []struct {
    Id string `json:"id"`
    Text string `json:"text"`
    Done bool `json:"done"`
    User struct {
      Id string `json:"id"`
      Name string `json:"name"`
    }
  }
}

func (c *Client) TodosQuery() (*TodosQueryPayload, error) {  
   	requestBody, err := json.Marshal(request{
		Query: TodosQuery,
	})

	if err != nil {
		return nil, err
	}

	resp, err := c.Post(c.Url, "application/json", bytes.NewBuffer(requestBody))     


	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		return nil, err
	}

	var payload TodosQueryPayload
	err = json.Unmarshal(body, &payload)

	if err != nil {
		return nil, err
	}

	return &payload, nil
}

var TodosQueryWithVariables = `query TodosQueryWithVariables ($userId: ID!) {
	todos(userId: $userId) {
		id
		text
		done
		user {
			id
			name
		}
	}
}
`


type TodosQueryWithVariablesInput struct {
  UserId string `json:"userId"`
}


type TodosQueryWithVariablesPayload struct {
  Todos []struct {
    Id string `json:"id"`
    Text string `json:"text"`
    Done bool `json:"done"`
    User struct {
      Id string `json:"id"`
      Name string `json:"name"`
    }
  }
}

func (c *Client) TodosQueryWithVariables(input TodosQueryWithVariablesInput) (*TodosQueryWithVariablesPayload, error) {  
   	requestBody, err := json.Marshal(request{
		Query: TodosQueryWithVariables, 
		Variables: input,
    	
	})

	if err != nil {
		return nil, err
	}

	resp, err := c.Post(c.Url, "application/json", bytes.NewBuffer(requestBody))     


	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		return nil, err
	}

	var payload TodosQueryWithVariablesPayload
	err = json.Unmarshal(body, &payload)

	if err != nil {
		return nil, err
	}

	return &payload, nil
}

